class_name CatalogoRealistas
extends RefCounted
## GERADO por tools/fatiar_realistas.gd — nao editar na mao.
##
## Caminhos literais de proposito: e assim que o auditor do
## `.pck` (tools/verify/pack_audit.py) enxerga estas cenas.

const POR_PACOTE := {
	"bordeaux_flat_1_corner_france": [
		"res://assets/realistas_prontos/bordeaux_flat_1_corner_france_00.scn",
	],
	"bordeaux_flat_2_corner_france": [
		"res://assets/realistas_prontos/bordeaux_flat_2_corner_france_00.scn",
	],
	"brownstone_building_set": [
		"res://assets/realistas_prontos/brownstone_building_set_00.scn",
		"res://assets/realistas_prontos/brownstone_building_set_01.scn",
		"res://assets/realistas_prontos/brownstone_building_set_02.scn",
		"res://assets/realistas_prontos/brownstone_building_set_03.scn",
		"res://assets/realistas_prontos/brownstone_building_set_04.scn",
		"res://assets/realistas_prontos/brownstone_building_set_05.scn",
		"res://assets/realistas_prontos/brownstone_building_set_06.scn",
		"res://assets/realistas_prontos/brownstone_building_set_07.scn",
		"res://assets/realistas_prontos/brownstone_building_set_08.scn",
		"res://assets/realistas_prontos/brownstone_building_set_09.scn",
		"res://assets/realistas_prontos/brownstone_building_set_10.scn",
		"res://assets/realistas_prontos/brownstone_building_set_11.scn",
		"res://assets/realistas_prontos/brownstone_building_set_12.scn",
		"res://assets/realistas_prontos/brownstone_building_set_13.scn",
		"res://assets/realistas_prontos/brownstone_building_set_14.scn",
		"res://assets/realistas_prontos/brownstone_building_set_15.scn",
		"res://assets/realistas_prontos/brownstone_building_set_16.scn",
		"res://assets/realistas_prontos/brownstone_building_set_17.scn",
		"res://assets/realistas_prontos/brownstone_building_set_18.scn",
		"res://assets/realistas_prontos/brownstone_building_set_19.scn",
		"res://assets/realistas_prontos/brownstone_building_set_20.scn",
		"res://assets/realistas_prontos/brownstone_building_set_21.scn",
		"res://assets/realistas_prontos/brownstone_building_set_22.scn",
		"res://assets/realistas_prontos/brownstone_building_set_23.scn",
		"res://assets/realistas_prontos/brownstone_building_set_24.scn",
		"res://assets/realistas_prontos/brownstone_building_set_25.scn",
	],
	"downtown_buildings": [
		"res://assets/realistas_prontos/downtown_buildings_00.scn",
		"res://assets/realistas_prontos/downtown_buildings_01.scn",
		"res://assets/realistas_prontos/downtown_buildings_02.scn",
		"res://assets/realistas_prontos/downtown_buildings_03.scn",
		"res://assets/realistas_prontos/downtown_buildings_04.scn",
		"res://assets/realistas_prontos/downtown_buildings_05.scn",
		"res://assets/realistas_prontos/downtown_buildings_06.scn",
		"res://assets/realistas_prontos/downtown_buildings_07.scn",
		"res://assets/realistas_prontos/downtown_buildings_08.scn",
		"res://assets/realistas_prontos/downtown_buildings_09.scn",
		"res://assets/realistas_prontos/downtown_buildings_10.scn",
		"res://assets/realistas_prontos/downtown_buildings_11.scn",
		"res://assets/realistas_prontos/downtown_buildings_12.scn",
		"res://assets/realistas_prontos/downtown_buildings_13.scn",
		"res://assets/realistas_prontos/downtown_buildings_14.scn",
		"res://assets/realistas_prontos/downtown_buildings_15.scn",
		"res://assets/realistas_prontos/downtown_buildings_16.scn",
		"res://assets/realistas_prontos/downtown_buildings_17.scn",
	],
	"european_buildings_pack3": [
		"res://assets/realistas_prontos/european_buildings_pack3_00.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_01.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_02.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_03.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_04.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_05.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_06.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_07.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_08.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_09.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_10.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_11.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_12.scn",
		"res://assets/realistas_prontos/european_buildings_pack3_13.scn",
	],
	"industrial_buildings_sets": [
		"res://assets/realistas_prontos/industrial_buildings_sets_00.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_01.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_02.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_03.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_04.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_05.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_06.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_07.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_08.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_09.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_10.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_11.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_12.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_13.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_14.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_15.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_16.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_17.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_18.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_19.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_20.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_21.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_22.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_23.scn",
		"res://assets/realistas_prontos/industrial_buildings_sets_24.scn",
	],
	"new_york_buildings": [
		"res://assets/realistas_prontos/new_york_buildings_00.scn",
		"res://assets/realistas_prontos/new_york_buildings_01.scn",
		"res://assets/realistas_prontos/new_york_buildings_02.scn",
		"res://assets/realistas_prontos/new_york_buildings_03.scn",
		"res://assets/realistas_prontos/new_york_buildings_04.scn",
		"res://assets/realistas_prontos/new_york_buildings_05.scn",
		"res://assets/realistas_prontos/new_york_buildings_06.scn",
		"res://assets/realistas_prontos/new_york_buildings_07.scn",
		"res://assets/realistas_prontos/new_york_buildings_08.scn",
		"res://assets/realistas_prontos/new_york_buildings_09.scn",
		"res://assets/realistas_prontos/new_york_buildings_10.scn",
		"res://assets/realistas_prontos/new_york_buildings_11.scn",
		"res://assets/realistas_prontos/new_york_buildings_12.scn",
		"res://assets/realistas_prontos/new_york_buildings_13.scn",
		"res://assets/realistas_prontos/new_york_buildings_14.scn",
		"res://assets/realistas_prontos/new_york_buildings_15.scn",
		"res://assets/realistas_prontos/new_york_buildings_16.scn",
	],
	"old_building_pack_lowpoly": [
		"res://assets/realistas_prontos/old_building_pack_lowpoly_00.scn",
		"res://assets/realistas_prontos/old_building_pack_lowpoly_01.scn",
		"res://assets/realistas_prontos/old_building_pack_lowpoly_02.scn",
	],
	"tenement_house": [
		"res://assets/realistas_prontos/tenement_house_00.scn",
		"res://assets/realistas_prontos/tenement_house_01.scn",
	],
}
